title: kataokaのブログ
baseurl: "/kataoka-blog"
url: "https://kataoka95.github.io"
lang: ja
locale: ja-JP
email:
description: >-
  kataokaのブログは、ロボカップジュニアに参加している中の人の進捗やつぶやきを載せるためのブログです。
  ぜひご覧ください
twitter_username: "@aki_rcjj"
github_username: "kataoka95"
minimal_mistakes_skin: default
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Asia/Tokyo

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "kataoka"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : ロボカップジュニア2年目のkataokaです。
  location: "滋賀県,日本"
  links:
    - label: "このサイト"
      icon: "fas fa-fw fa-link"
      url: "https://kataoka95.github.io/kataoka-blog/"
    - label: "X"
      icon: "	fab fa-fw fa-x-twitter"
      url: "https://x.com/aki_rcjj"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kataoka95"

footer:
  links:
    - label: "X"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/aki_rcjj"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kataoka95"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

date_format: "%Y年%m月%d日"
